export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  analysisPrimaryModel: process.env.AI_ANALYSIS_PRIMARY_MODEL ?? "gemini-3-flash-preview",
  analysisFallbackModel: process.env.AI_ANALYSIS_FALLBACK_MODEL ?? "gpt-5-mini",
  tryOnPrimaryImageModel: process.env.AI_TRYON_PRIMARY_IMAGE_MODEL ?? "MODEL_GPT_IMAGE_2",
  tryOnFallbackImageModel: process.env.AI_TRYON_FALLBACK_IMAGE_MODEL ?? "",
  tryOnImageQuality: process.env.AI_TRYON_IMAGE_QUALITY ?? "medium",
};
